### PR TITLE
Add support to build libraries

### PR DESCRIPTION
**Pull request by trimpim**

### CODE REVIEW

**Comment by nfeske** [comment]
Thanks @trimpim for the pull request. I'm going though the commits step by step.

I merged https://github.com/nfeske/goa/pull/27/commits/af4b9ceaae9a8fe31ba0b55e54d68e816019f0a4 as is.

I would leave out https://github.com/nfeske/goa/pull/27/commits/7396859f609cb81273ad1fa415e263ddc9fd454d because the depot user for the `run step` is normally not the same as the depot user for the other steps. The run step refers to packages matching the last official Sculpt version. So they eventually will refer to the official genodelabs packages. Until now, I used to refer to nfeske to slightly decouple Goa from the genodelabs releases. Whereas the runtime packages should be understood as part of infrastructure of Goa, the `--depot-user` refers to the individual Goa user. I can see that it might be useful to make the runtime packages configurable as well - especially when using Goa for targeting Genode versions in-between Sculpt releases. But this needs to be a different configuration argument.

**Comment by nfeske** [comment]
Merged https://github.com/nfeske/goa/commit/ec4677e5de20d1f7ab8c354f5c6afbb236ca8138 as is.

Merged https://github.com/nfeske/goa/commit/6be4c61488588a13ef20c05eac92c9f0ee3e8867 with the fixup included. Could you share why the changes of the check_abi and abi_symbol tools (compared to the upstream version) are needed? I noticed https://github.com/genodelabs/genode/issues/4764 but it gives no reasoning.

**Comment by nfeske** [comment]
Merged https://github.com/nfeske/goa/commit/5af2d03cc97ab915898b222c9232aae9bf9d5dad along with the fixup https://github.com/nfeske/goa/commit/37392e62f7791e76bdf3f80c792cfcbe55008fff. @trimpim do you approve the changes of the fixup?

**Comment by nfeske** [comment]
I also merged https://github.com/nfeske/goa/commit/4eeb86d54816de1973cdbe6c58e7c8acde951aa6 and https://github.com/nfeske/goa/commit/7c9a879ded1fd3f09f007089d6588d1db1f12f0d but I wonder if those shouldn't better be fixups to https://github.com/nfeske/goa/commit/5af2d03cc97ab915898b222c9232aae9bf9d5dad as they seemingly contain follow-up fixes?

**Comment by nfeske** [comment]
Thank you Pirmin for this excellent commit series and the much anticipated new feature!

I particularly like your sensible choices like the naming and content of the api file. Also, I appreciate the new bits of documentation, which illustrate quite well how natural the new feature was integrated.

Admittedly, I have merely reviewed the commits but haven't tested the new feature. How do you think of adding a simple example to goa/examples/ that contains the important bits and pieces, namely a symbols file, a CMakeList.txt file, an API header and a simple compilation unit implementing the API? I think this could be a valuable point of reference for future users.

**Comment by trimpim** [comment]
> Merged [ec4677e](https://github.com/nfeske/goa/commit/ec4677e5de20d1f7ab8c354f5c6afbb236ca8138) as is.
> 
> Merged [6be4c61](https://github.com/nfeske/goa/commit/6be4c61488588a13ef20c05eac92c9f0ee3e8867) with the fixup included. Could you share why the changes of the check_abi and abi_symbol tools (compared to the upstream version) are needed? I noticed [genodelabs/genode#4764](https://github.com/genodelabs/genode/issues/4764) but it gives no reasoning.

@nfeske the reason for this is due to the fact, that I failed to handle the output of the tool and place it in the symbols file. I'm in for leaving this out, if the original tool from upstream can be made to produce the correct symbols file.

**Comment by trimpim** [comment]
> I would leave out [7396859](https://github.com/nfeske/goa/commit/7396859f609cb81273ad1fa415e263ddc9fd454d) because the depot user for the `run step` is normally not the same as the depot user for the other steps.

I'm fine with that.

**Comment by trimpim** [comment]
> Merged [5af2d03](https://github.com/nfeske/goa/commit/5af2d03cc97ab915898b222c9232aae9bf9d5dad) along with the fixup [37392e6](https://github.com/nfeske/goa/commit/37392e62f7791e76bdf3f80c792cfcbe55008fff). @trimpim do you approve the changes of the fixup?

I agree with the fixup, Thanks for fixing my style errors and typos :-)

**Comment by trimpim** [comment]
> I also merged [4eeb86d](https://github.com/nfeske/goa/commit/4eeb86d54816de1973cdbe6c58e7c8acde951aa6) and [7c9a879](https://github.com/nfeske/goa/commit/7c9a879ded1fd3f09f007089d6588d1db1f12f0d) but I wonder if those shouldn't better be fixups to [5af2d03](https://github.com/nfeske/goa/commit/5af2d03cc97ab915898b222c9232aae9bf9d5dad) as they seemingly contain follow-up fixes?

I agree, that they should be fixups. The only reason I added them separately is, that I wasn't sure, how far along you were with your review and did not want for you to have to start over. Committing then as fixups would have made this clear.

**Comment by trimpim** [comment]
> aming and content of the api file. Also, I appreciate the new bits of documentation, which illustrate quite well how natural the new feature was integrated.

I currently don't have a simple example, but I'll look for one and provide a commit that adds this.

**Comment by nfeske** [comment]
Thank you @trimpim for the super quick response. I have force-pushed the consolidated commits to staging now.

> [...] I failed to handle the output of the tool and place it in the symbols file. I'm in for leaving this out, if the original tool from upstream can be made to produce the correct symbols file.

Let us keep you current version for now locally in Goa. We can try to revert the tools to the original version invoked via Tcl's `exec` command (instead of `source`ing the scripts) at a subsequent step. But that technical detail should not stand in the way of this pull request.

**Comment by trimpim** [comment]
@nfeske I have updated my branch to your staging and added the following two commits:

7a19b8cc2e63a21e1ccec88f13106347a218f3b0 this fixes a typo (`api` instead of `abi`) and changes I made because of that.

8f6996aa39d9841d753f51ff6a435aa12c32fb9b adds the small library `spdlog` as an example. Building the library builds fine, the problem is, when I want to build the example project `spdlog_test` that uses this library it fails with 4 missing symbols which probably belong to `stdcxx` (they are listed in the current commit).
I see the following solutions:
 - create a fix in upstream Genode repository
 - search an other library as example
 - do not provide `spdlog_test` this doesn't solve the issue, if some one wants to use this library
What do you suggest to do?

**Comment by nfeske** [comment]
Thanks for the fixup, which I promptly added to the staging branch.

Regarding your question, I was thinking of a contrived example that is as simple as possible, just to illustrate how CMake, the api file, a symbols file, a header file, and an implementation file work together. For this narrow purpose, the import step can be entirely skipped. A simple API with one function (like checking if a number is a prime number or something similar) would suffice.

**Comment by trimpim** [comment]
@nfeske 46c3880d277f78de4c3fed65d41dc6c053642a09 adds a simple example as you have outlined it.

**Comment by nfeske** [comment]
> https://github.com/nfeske/goa/commit/46c3880d277f78de4c3fed65d41dc6c053642a09 adds a simple example as you have outlined it.

That's exactly what I had in mind. It works excellent and can serve as a very good blueprint.

Thanks @trimpim for wrapping up the library feature so nicely. :)

I think we are ready to master, are we?

**Comment by trimpim** [comment]
@nfeske yes, I think, this is now ready for master.

**Comment by nfeske** [comment]
Thank you for the confirmation. I just updated the master branch.

**Pull request closed without merging**
