### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by blitz**
This PR fixes the usage instructions and removes hardcoded paths from shebang lines.

### CODE REVIEW

**Comment by chelmuth** [comment]
The first commits reminds me of a discussion in Genode https://github.com/genodelabs/genode/issues/3421 Are there other distros beside Nix supporting this kind of usage of */usr/bin/env* entirely?

**Comment by blitz** [comment]
The usage of `env` without `-S` is supported since the beginning of time. That's why I converted only those that don't need it.

For the `-S` parameter, I first noticed that Ubuntu LTS ships old `env` that can't do this when I gave a script I wrote on my Fedora system to Ubuntu-using colleagues. So this is definitely not something that you can blindly do yet. *sigh*

Regarding `/usr/bin/env` in general, I started using this for all scripts I write back in FreeBSD days where a lot of tools live in `/usr/local`. But also in my former job pretty much everything had to come via PATH instead of hardcoded variables due to the way software was distributed across machines. Nix is certainly not alone here.

If the goal is to get the tooling working for as many people as possible then using `env` definitely helps. For me personally solving #1 would also remove this problem, because then I can package Goa and patch the shebang lines on the fly.

**Comment by chelmuth** [comment]
@blitz Ah, I see: It works for `tclsh` and `expect` (without additional parameters on the shebang line) but breaks for `make -f`. Thanks for the explanation.

**Comment by nfeske** [comment]
Thanks for the fixes and for the explanation of the /usr/bin/env situation. Since the `make -f` case does not apply here, we are safe here. I merged both commits.

**Pull request closed without merging**
